Task/add tmbd api
andreyshilov0/back-end-my-favorite-movies pull request #2
Opened 2023-05-10 08:49 UTC by andreyshilov0

2023-05-10 09:27 UTC, reshetov requested changes

2023-05-10 09:27 UTC, reshetov commented on app/controllers/application_controller.rb
> +class ApplicationController < ActionController::API
Это ты сам менял или генератор?

2023-05-10 09:27 UTC, reshetov commented on app/services/tmbd_api_client.rb
> +  def request_genres_movie
1. request_. не нужно в именах и так понятно что ты данные запрашиваешь
2. https://engblog.ru/plural-of-nouns
3. у тебя тут и ниже код повторяется, это нарушение DRY (Don't repeat youself!), убери дубляж, можно просто создать один универсальный метод и вызвать его в нужными параметрами

2023-05-10 09:28 UTC, andreyshilov0 commented on app/controllers/application_controller.rb
> +class ApplicationController < ActionController::API
Сам менял, в доке было написано

2023-05-12 06:56 UTC, reshetov requested changes

2023-05-12 06:56 UTC, reshetov commented on app/services/tmdb_api.rb
> +    Faraday.new(url: INSTANCE_URL, params: { api_key: API_KEY, language: 'en-US' }, headers: { 'Content-Type' => 'application/json' })
Добавь тут мемоизацию (https://tadhao.medium.com/memoization-in-rails-1e08a9151ce6),  достаточно самой базовой -> @a ||= ...

2023-05-12 06:56 UTC, reshetov commented on app/services/tmdb_api.rb
> +    @data = data
Зачем эта строка? Ты же нигде не обращаешся к этой переменной на прямую, а метод сам вернет последнее присвоение

2023-05-12 06:56 UTC, reshetov commented on app/services/tmdb_api.rb
> +    @response_api_data = response_api_data
Тот же вопрос что и коментом выше

2023-05-12 06:56 UTC, reshetov commented on app/services/tmdb_api.rb
> +    @response_api_data = response_api_data
Тот же вопрос что и коментом выше

2023-05-12 06:56 UTC, reshetov commented on app/services/tmdb_api.rb
> +    @response_api_data = response_api_data
Тот же вопрос что и коментом выше

2023-05-12 06:56 UTC, reshetov commented on app/services/tmdb_api.rb
> +    @response_api_data = response_api_data['total_pages']
Тот же вопрос что и коментом выше

2023-05-12 08:07 UTC, reshetov requested changes

2023-05-12 08:07 UTC, reshetov commented on app/services/tmdb_api.rb
> +    response_api_data = get_api_data('genre/movie/list')
Здесь и ниже:
Подумай response_api_data переменная для чего? Ее использует кто-то?

2023-05-12 08:24 UTC, merged