Task/add graphql
andreyshilov0/back-end-my-favorite-movies pull request #3
Opened 2023-05-16 10:38 UTC by andreyshilov0

2023-05-16 12:30 UTC, reshetov requested changes

2023-05-16 12:30 UTC, reshetov commented on app/graphql/mutations/favorite_movie_add.rb
> +    def resolve(id:, title: nil, year: nil, description: nil, image_url: nil, watched: false, user_id: nil)
При таком подходе тебе придется отправлять кучу данных с фронта (точнее ВЕСЬ фильм)
Нужно передавать только movie_id и по нему уже тут отдельным запросом получать фильм хотя бы

2023-05-16 12:30 UTC, reshetov commented on app/graphql/mutations/favorite_movie_add.rb
> +          favorite_movie:,
Какой смысл отправлять пустые данные?

2023-05-16 12:30 UTC, reshetov commented on app/graphql/mutations/favorite_movie_delete.rb
> +      favorite_movie = ::FavoriteMovie.find(id)
:: не нужно, у тебя и так объект в глобальном namespace

2023-05-16 12:30 UTC, reshetov commented on app/graphql/types/genre_type.rb
> +    field :user_id, Integer, null: false
Это не нужно, жанры ты и так отдаешь только для нужного пользователя

2023-05-16 12:30 UTC, reshetov commented on app/graphql/types/favorite_movie_type.rb
> +    field :user_id, Integer, null: false
Не нужно

2023-05-16 12:30 UTC, reshetov commented on app/graphql/types/favorite_movie_type.rb
> +    field :created_at, GraphQL::Types::ISO8601DateTime, null: false
Зачем тебе эти данные в ответе?

2023-05-16 12:30 UTC, reshetov commented on app/graphql/types/genre_type.rb
> +    field :created_at, GraphQL::Types::ISO8601DateTime, null: false
Зачем тебе эти данные в ответе?

2023-05-16 12:30 UTC, reshetov commented on app/graphql/types/query_type.rb
> +    field :users, [Types::UserType], null: false,
Что-то тут у тебя мешались "в кучу кони, люди",  разнеси объекты из для разных моделей по модулям и тут их просто инклудь

2023-05-16 12:30 UTC, reshetov commented on app/graphql/types/query_type.rb
> +    def users
Зачем?

2023-05-16 12:30 UTC, reshetov commented on app/graphql/types/query_type.rb
> +    field :user, Types::UserType, null: false do
Зачем?

2023-05-16 12:30 UTC, reshetov commented on app/graphql/types/query_type.rb
> +    def user(id:)
Тот же вопрос

2023-05-16 12:30 UTC, reshetov commented on app/graphql/types/query_type.rb
> +      FavoriteMovie.all
Зачем?

2023-05-16 12:30 UTC, reshetov commented on app/graphql/types/query_type.rb
> +                                       description: 'List genres'
Описание в локали тут и далее везде

2023-05-16 12:30 UTC, reshetov commented on app/graphql/types/query_type.rb
> +    field :favorite_movie, [Types::FavoriteMovieType], null: false do
Зачем?

2023-05-16 12:30 UTC, reshetov commented on app/graphql/types/query_type.rb
> +    field :favorite_movie_discover, [Types::MovieParametersType], null: false do
Зачем?

2023-05-16 12:30 UTC, reshetov requested changes
Comments

2023-05-16 12:32 UTC, andreyshilov0 commented on app/graphql/mutations/favorite_movie_delete.rb
> +      favorite_movie = ::FavoriteMovie.find(id)
это видимо генератор накинул

2023-05-18 08:02 UTC, reshetov requested changes

2023-05-18 08:02 UTC, reshetov commented on app/graphql/mutations/favorite_genre_add.rb
> +      genre_id = favorite_genres.fetch(genres_id)['id']
А если тебе нужно будет 15 атрибутов заполнить - ты будет 15 раз одну и туже переменную дергать?
Вытащи в переменную один раз и используй ее

2023-05-18 08:02 UTC, reshetov commented on app/graphql/mutations/favorite_genre_add.rb
> +      favorite_genre = Genre.new("id": genre_id, "title": genres_name, "user_id": 1)
1. "" без интерполяции не используется (используется ''), но тут лучше использовать вообще символы.
2. user_id - у тебя только один пользователь в системе? И у него всегда ID = 1?  Тут нужно через ассоциации делать. У тебя есть модель user, у нее has_many  favoriteGenres вот и нужно от этого играть
Добавь в ApplicationConteoller метод current_user который возвращает пользователя (потом заменим на нормальны метод)   и тут уже везде работай с current_user.favorite_genres

2023-05-18 08:02 UTC, reshetov commented on app/graphql/mutations/favorite_genre_add.rb
> +          favorite_genres:,
Для чего тебе это?

2023-05-18 08:02 UTC, reshetov commented on app/graphql/mutations/favorite_movie_add.rb
> +      id = favorite_movie_by_id['id']
См. коменты выше

2023-05-18 08:02 UTC, reshetov commented on app/graphql/queries/favorite_movie.rb
> +    def resolve(id:)
Для чего это метод? Где именно тебе может понадобится достать избранный фильм по ID?

2023-05-18 08:02 UTC, reshetov commented on app/graphql/queries/genres.rb
> +      ::Genre.all
Для чего этот метод? 
В схеме базы у тебя в таблице лежат titile и user_id (https://github.com/andreyshilov0/back-end-my-favorite-movies/blob/main/db/schema.rb#L29) В каком месте они тебе все могут понадобится?

2023-05-18 08:02 UTC, reshetov commented on app/services/tmdb_api.rb
> +  def self.instance_faraday_url
Заменить все методы на методы класса - так себе разобраться в проблеме.
А что если я тебе скажу что в этом методе ты делаешь подключение и если оно отвалится, то без перезапуска приложения ты уже ничего с ним не сделаешь (метод класса потому что он один)
Лучше верни как было и просто вызывай методы через инстанс

2023-05-18 08:02 UTC, reshetov commented on app/graphql/queries/favorite_movie.rb
> +    description I18n.t('list_favorite_movies')
А этот ключ где?

2023-05-18 15:31 UTC, andreyshilov0 commented on app/graphql/queries/genres.rb
> +      ::Genre.all
мне кажется это при создании миграций докидывалось автоматически когда я модель определял, потому что сам я не добавлял в таблицу user_id

2023-05-19 03:01 UTC, reshetov requested changes

2023-05-19 03:01 UTC, reshetov commented on app/controllers/application_controller.rb
> +    # Не совсем понятна модель работы, к примеру, у нас есть модель User, тобишь
Этот метод сейчас по сути заглушка, потом его заменит метод авторизации (почитай про device гем)
Он не должен быть классовым, каждый запрос создает свой экземпляр контроллера ApplicationController. И вызывать его нужно как просто current_user

2023-05-19 03:01 UTC, reshetov commented on app/graphql/mutations/favorite_genre_add.rb
> +                                  user_id: ApplicationController.current_user)
См. выше комментарий

2023-05-19 03:01 UTC, reshetov commented on app/graphql/mutations/favorite_genre_add.rb
> +      return if favorite_genre.save
Ну ты хоть сам объект возвращай когда он сохранен, раньше ты просто пустую переменную отдавал. В этом была суть моего комментария

2023-05-19 03:01 UTC, reshetov commented on app/graphql/mutations/favorite_movie_add.rb
> +      return if favorite_movie.save
Тоже самое

2023-05-19 03:01 UTC, reshetov commented on app/graphql/queries/favorite_movies.rb
> +      ::FavoriteMovie.all
Сейчас у тебя этот метод отдает ВСЕ фильмы ВСЕХ пользователей. Как думаешь это правильно? Или стоит отдавать только фильмы для текущего пользователя

2023-05-19 03:01 UTC, reshetov commented on app/services/tmdb_api.rb
> +  # Тоесть логика экземпляра метода в том чтобы каждый раз создавать новый экземпляр и обрабатывать всё занового через него?
Да, в этом нет ничего плохого

2023-05-19 03:01 UTC, reshetov commented on app/services/tmdb_api.rb
> +  # Тоесть логика экземпляра метода в том чтобы каждый раз создавать новый экземпляр и обрабатывать всё занового через него?
Точнее есть варианты когда нужно чтобы был только один экземпляр класса (читай паттерн Singleton) но это не твой случай

2023-05-19 08:59 UTC, andreyshilov0 commented on app/graphql/mutations/favorite_genre_add.rb
> +      return if favorite_genre.save
там другая немного ситуация, я передавал переменную , а рубокоп сам решил что эту переменную можно оставить и так, метод работал исправно, я поэтому и не обратил видимо внимание)

2023-05-19 12:37 UTC, reshetov requested changes

2023-05-19 12:37 UTC, reshetov commented on app/graphql/mutations/favorite_genre_add.rb
> +      response_app_controller = ApplicationController.new
Не нужно по идее это, у тебя все контроллеры от него унаследованы, поэтому просто используй current_user и все

2023-05-19 12:37 UTC, reshetov commented on app/graphql/mutations/favorite_genre_add.rb
> +      current_user = response_app_controller.current_user
См выше

2023-05-19 12:37 UTC, reshetov commented on app/graphql/mutations/favorite_genre_add.rb
> +                                 user_id: current_user_id)
Я же выше писал что нужно has_many использовать. Почитай про has_many .build метод

2023-05-19 12:37 UTC, reshetov commented on app/graphql/mutations/favorite_genre_add.rb
> +        favorite_genre:,
Скинь фото того что этот метод возвращает. Или я что-то не понимаю или ты меня

2023-05-19 12:37 UTC, reshetov commented on app/graphql/mutations/favorite_movie_add.rb
> +      response_app_controller = ApplicationController.new
Также ситуация что и выше

2023-05-19 13:14 UTC, andreyshilov0 commented on app/graphql/mutations/favorite_genre_add.rb
> +      response_app_controller = ApplicationController.new
Как я понимаю метод current_user нужно сделать методом класса через self, потому что в другом случаем он не может найти метод без создания экземпляра.

2023-05-19 13:34 UTC, andreyshilov0 commented on app/graphql/mutations/favorite_genre_add.rb
> +        favorite_genre:,
Тут я попутал немного с обработкой ошибок, убрал , он не нужен

2023-05-19 14:36 UTC, andreyshilov0 commented on app/graphql/mutations/favorite_genre_add.rb
> +      response_app_controller = ApplicationController.new
Оставил комментарии в коде

2023-05-23 08:14 UTC, reshetov requested changes

2023-05-23 08:14 UTC, reshetov commented on app/controllers/graphql_controller.rb
> +      # current_user: current_user,
current_user: current_user,

2023-05-23 08:14 UTC, reshetov commented on app/controllers/application_controller.rb
> +  def self.current_user
Убери self

2023-05-23 08:14 UTC, reshetov commented on app/graphql/mutations/favorite_genre_add.rb
> +      new_favorite_genres = TmdbApi.new
Название

2023-05-23 08:14 UTC, reshetov commented on app/graphql/mutations/favorite_genre_add.rb
> +      current_user = ApplicationController.current_user
current_user = context[:current_user]

2023-05-23 08:14 UTC, reshetov commented on app/graphql/mutations/favorite_genre_add.rb
> +                                 user_id: current_user_id)
user_id: current_user_id - не нужно

2023-05-23 08:14 UTC, reshetov commented on app/graphql/mutations/favorite_genre_add.rb
> +      current_user_id = current_user.id
+

2023-05-23 08:14 UTC, reshetov commented on app/graphql/mutations/favorite_genre_add.rb
> +      favorite_genres = new_favorite_genres.genres_movie['genres']
Я не понимаю

2023-05-23 08:14 UTC, reshetov commented on app/graphql/mutations/favorite_genre_add.rb
> +      genre_parameters = favorite_genres.fetch(genres_id)
+

2023-05-23 08:14 UTC, reshetov commented on app/graphql/mutations/favorite_genre_add.rb
> +      favorite_genre = current_user.genres.build(id: genre_parameters['id'], title: genre_parameters['name'],
+

2023-05-23 08:14 UTC, reshetov commented on app/graphql/mutations/favorite_genre_delete.rb
> +      favorite_genre = Genre.find(id)
find(123) -> genre -> exception
find_by(id: 123) -> genre -> nil

2023-05-23 08:14 UTC, reshetov commented on app/graphql/mutations/favorite_movie_add.rb
> +      response_movie_by_id = TmdbApi.new
+

2023-05-23 08:14 UTC, reshetov commented on app/graphql/mutations/favorite_movie_add.rb
> +      response_movie_by_id = TmdbApi.new
BaseMutation -> tmdb_api (TmdbApi.new) @a ||=

2023-05-23 08:14 UTC, reshetov commented on app/graphql/queries/favorite_movies.rb
> +      response_app_controller = ApplicationController.current_user
+

2023-05-23 08:14 UTC, reshetov commented on app/graphql/queries/genres.rb
> +      response_app_controller = ApplicationController.current_user
+

2023-05-23 08:14 UTC, reshetov commented on app/services/tmdb_api.rb
> +    instance_faraday_url ||= Faraday.new(url: INSTANCE_URL, params: { api_key: API_KEY, language: 'en-US' },
@ верни

2023-05-23 08:14 UTC, reshetov commented on app/services/tmdb_api.rb
> +    response_api_data = TmdbApi.new
?

2023-05-23 08:14 UTC, reshetov commented on app/services/tmdb_api.rb
> +    response_api_data = TmdbApi.new
?

2023-05-23 08:14 UTC, reshetov commented on app/services/tmdb_api.rb
> +    response_api_data = TmdbApi.new
?

2023-05-23 08:14 UTC, reshetov commented on app/services/tmdb_api.rb
> +    response_api_data = TmdbApi.new
?

2023-05-23 08:14 UTC, reshetov commented on app/services/tmdb_api.rb
> +    response_api_data = TmdbApi.new
?

2023-05-23 08:14 UTC, reshetov commented on config/initializers/cors.rb
> +Rails.application.config.middleware.insert_before 0, Rack::Cors do
Remove

2023-05-24 06:09 UTC, reshetov requested changes

2023-05-24 06:09 UTC, reshetov commented on .rubocop.yml
> -Style/FrozenStringLiteralComment:
Тут ты наоборот ты включил добавление. Те отключил его пропуск

2023-05-24 06:09 UTC, reshetov commented on app/services/tmdb_api.rb
> +    response = tmdb_api.instance_faraday_url.get(url, params)
Нет, я же сказал что у тебя уже есть он

2023-05-24 16:22 UTC, reshetov approved these changes

2023-05-24 16:22 UTC, merged